spring:
  application:
    name: quote-service
  datasource:
    url: jdbc:mysql://localhost:3306/quotes?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Taipei
    username: root
    password: 123
  jackson:
    time-zone: Asia/Taipei
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  task:
    scheduling:
      pool:
        size: 1

mybatis:
  mapper-locations: classpath:/com/org/quoteservice/server/adapter/out/persistence/mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    org.springframework.boot.autoconfigure: INFO
    root: INFO
    org.springframework.jdbc.support.JdbcTransactionManager: DEBUG
  charset:
    console: UTF-8
    file: UTF-8

nats:
  url: nats://127.0.0.1:4222
