name: yahoo_etf_daily
source: yahoo
type: etf
symbols:
  - "0050"
  - "0056"
  - "006208"
  - "00692"
  - "00713"
  - "00752"
  - "00850"
  - "00878"
  - "00881"
  - "00882"
  - "00891"
  - "00894"
  - "00896"
  - "00900"
  - "00904"
  - "00907"
  - "00909"
  - "00915"
  - "00919"
  - "00929"
every: "24h"
batch_size: 10
batches_per_tick: 1
max_workers: 3
max_concurrency: 2
output_dir: "out/yahoo"
write_json: false
write_json_every_ticks: 5
