name: yahoo_etf_daily
source: yahoo
type: etf
symbols:
  - "0050"
  - "0051"
  - "0052"
  - "0053"
  - "0054"
  - "0055"
  - "0056"
  - "0057"
  - "0058"
  - "0059"
  - "006201"
  - "006203"
  - "006208"
  - "00631L"
  - "00632R"
  - "00633L"
  - "00637L"
  - "00638R"
  - "00701"
  - "00713"
every: "24h"
batch_size: 10
batches_per_tick: 1
max_workers: 3
max_concurrency: 2
output_dir: "out/yahoo"
write_json: false
write_json_every_ticks: 5
